name: Build SafeHaven Vault APK

on:
  push:
    branches: [master]

jobs:
  build:
    name: Flutter Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SafeHavenVault-APK
          path: build/app/outputs/flutter-apk/app-release.apk
